
version: '3.8'

services:
  map-choise-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
      - ./coordinates.txt:/app/coordinates.txt
      - ./splits.html:/app/splits.html
    restart: unless-stopped
    container_name: map-choise-app

